Imports System.Globalization
Imports System.Data
Imports Telerik.Web.UI

Partial Class Edicion_ConsultaEmisiones
    Inherits System.Web.UI.Page
    Private oper As New operation
    Private cStringWhere As String = ""
    Dim ciNewFormat As New CultureInfo(CultureInfo.CurrentCulture.ToString())
    Protected Sub Page_Init(sender As Object, e As EventArgs) Handles Me.Init
        Dim ciNewFormat As New CultureInfo(CultureInfo.CurrentCulture.ToString())

        ciNewFormat.DateTimeFormat.ShortDatePattern = "dd/MM/yyyy"
        System.Threading.Thread.CurrentThread.CurrentCulture = ciNewFormat
    End Sub

    Protected Sub Page_Load(sender As Object, e As EventArgs) Handles Me.Load
        If Not IsPostBack Then
            txtIdUsuario.Text = Session("IdUsuario")

            'Filtro por defecto
            Dim cStatus As String = "Vigente"
            cStringWhere = String.Format("[Estatus]='{0}'", cStatus)

            Dim editor As New RadFilterTextFieldEditor()
            RadFilter1.FieldEditors.Add(editor)

            editor.FieldName = "Estatus Emisión"
            editor.DataType = GetType(String)

            Dim expr As New RadFilterEqualToFilterExpression(Of String)("Estatus")
            ' Valor Por Defecto
            expr.Value = cStatus

            RadFilter1.RootGroup.Expressions.Add(expr)
            RadFilter1.ApplyButtonText = "Aplicar Filtro"
            DataRefresh()

            Dim expression As GridGroupByExpression = New GridGroupByExpression
            Dim gridGroupByField As GridGroupByField = New GridGroupByField

            With RadGrid1
                .Culture = New CultureInfo("es-DO")
                .AlternatingItemStyle.BackColor = System.Drawing.ColorTranslator.FromHtml("#F1F5FB")


                Try
                    gridGroupByField = New GridGroupByField
                    gridGroupByField.FieldName = "Emisor"
                    gridGroupByField.HeaderText = "Emisor"
                    gridGroupByField.HeaderValueSeparator = " : "
                    gridGroupByField.FormatString = "<strong>{0}</strong>"
                    expression.SelectFields.Add(gridGroupByField)

                    gridGroupByField = New GridGroupByField
                    gridGroupByField.FieldName = "Emisor"

                    expression.GroupByFields.Add(gridGroupByField)
                    .MasterTableView.GroupByExpressions.Add(expression)

                Catch ex As Exception

                Finally
                    RadGrid1.Rebind()
                End Try

            End With
            AnchoColumna()
            LlenarInformacionListaFiltros()


            oper.GenerarSeguimientoActividadUsuario(Session("IdUsuario"), "Ingreso a Consulta: Emisiones", "Consulta de Emisiones", "")

        End If

        If Request.Params("__EVENTTARGET") = "ActualizarFiltros" Then
            LlenarInformacionListaFiltros1()
            If Session("NombreConsultaTemp") <> "" Then
                txtNombreConsultaUsuario.Text = Session("NombreConsultaTemp")
                Page.Header.Title = "Consulta de emisiones -> " & Session("NombreConsultaTemp")
                CargarInformacionFiltro(Session("NombreConsultaTemp"))
                Session.Remove("NombreConsultaTemp")
            End If
            RadWindowManager1.Windows.Clear()

            Exit Sub

        End If

        If Session("FiltroBorrado") = 1 Then
            txtIdConsulta.Text = 0
            txtNombreConsultaUsuario.Text = ""
            Session.Remove("FiltroBorrado")
        End If

        If txtNombreConsultaUsuario.Text <> "" Then
            Page.Header.Title = "Consulta de Emisiones -> " & txtNombreConsultaUsuario.Text
        End If


    End Sub
    Protected Sub RadFilter1_ApplyExpressions(sender As Object, e As RadFilterApplyExpressionsEventArgs) Handles RadFilter1.ApplyExpressions
        Try
            ciNewFormat.DateTimeFormat.ShortDatePattern = "MM/dd/yyyy"
            Threading.Thread.CurrentThread.CurrentCulture = ciNewFormat

            Dim provider As New RadFilterSqlQueryProvider()
            provider.ProcessGroup(e.ExpressionRoot)
            cStringWhere = provider.Result.Trim

            ciNewFormat.DateTimeFormat.ShortDatePattern = "dd/MM/yyyy"
            Threading.Thread.CurrentThread.CurrentCulture = ciNewFormat

            DataRefresh()

        Catch ex As Exception
        End Try
    End Sub
    Sub DataRefresh()
        SqlvConsultaEmisiones.SelectCommandType = SqlDataSourceCommandType.StoredProcedure
        SqlvConsultaEmisiones.SelectParameters("SqlWhere").DefaultValue = cStringWhere
        SqlvConsultaEmisiones.SelectCommand = "SP_ConsultaEmisiones"
    End Sub

    Sub AnchoColumna()
        Dim i As Integer = 0
        While i < RadGrid1.MasterTableView.AutoGeneratedColumns.Length
            TryCast(RadGrid1.MasterTableView.AutoGeneratedColumns(i), GridBoundColumn).DataFormatString = "<nobr>{0}</nobr>"
            System.Math.Max(System.Threading.Interlocked.Increment(i), i - 1)
        End While
        RadGrid1.MasterTableView.Rebind()
    End Sub

    Protected Sub RadToolBar1_ButtonClick(sender As Object, e As RadToolBarEventArgs) Handles RadToolBar1.ButtonClick, RadToolBar2.ButtonClick
        If e.Item.Value <> "" Then

            If e.Item.Value = 0 Then 'Mover

                InjectScriptLabelImprimir.Text = "<script>ventanaSecundaria('../Consultas/ConsultaEmisiones.aspx','1000','600')</" + "script>"

            ElseIf e.Item.Value = 1 Then 'Cancelar
                InjectScriptLabel.Text = "<script>CerrarVentana()</" + "script>"

            ElseIf e.Item.Value = 2 Then 'Guardar
                Dim SavePersister As New GridSettingsPersister(RadGrid1)
                Dim cSettingGrid As String = ""

                cSettingGrid = SavePersister.SaveSettings()
                Session("EstruturaGrid") = SavePersister.SaveSettings()
                Session("Filtro") = RadFilter1.SaveSettings()
                Dim MyWindow As New Telerik.Web.UI.RadWindow
                MyWindow.NavigateUrl = "NombreConsultaUsuario.aspx?ID=" & txtIdConsulta.Text & "&NC=ConsultaEmisiones&U=" & txtIdUsuario.Text & "&NCU=" & txtNombreConsultaUsuario.Text ' & "&F=" & RadFilter1.SaveSettings()
                MyWindow.VisibleOnPageLoad = True
                MyWindow.AutoSize = True
                RadWindowManager1.Windows.Clear()
                RadWindowManager1.Windows.Add(MyWindow)

            ElseIf e.Item.Value = 4 Then 'Exportar excel

                ciNewFormat.DateTimeFormat.ShortDatePattern = "yyyy/MM/dd"
                System.Threading.Thread.CurrentThread.CurrentCulture = ciNewFormat

                RadGrid1.MasterTableView.PageSize = RadGrid1.Items.Count
                With RadFilter1
                    .FireApplyCommand()
                End With
                RadGrid1.MasterTableView.ExportToExcel()

                ciNewFormat.DateTimeFormat.ShortDatePattern = "dd/MM/yyyy"
                System.Threading.Thread.CurrentThread.CurrentCulture = ciNewFormat


            ElseIf e.Item.Value = 5 Then 'Exportar pdf
                RadGrid1.MasterTableView.PageSize = RadGrid1.Items.Count
                With RadFilter1
                    .FireApplyCommand()
                End With
                RadGrid1.MasterTableView.ExportToPdf()
            ElseIf e.Item.Value = 6 Then 'Exportar csv
                RadGrid1.MasterTableView.PageSize = RadGrid1.Items.Count
                With RadFilter1
                    .FireApplyCommand()
                End With
                RadGrid1.MasterTableView.ExportToCSV()

            End If
        Else

            If e.Item.Text <> "" Then
                txtNombreConsultaUsuario.Text = e.Item.Text
                Page.Header.Title = "Consulta de Emisiones -> " & e.Item.Text
                CargarInformacionFiltro(e.Item.Text)
            End If

        End If
    End Sub
    Protected Sub CargarInformacionFiltro(cNombreConsultaUsuario As String)

        Dim ds As DataSet = oper.ExDataSet("SELECT idConsulta,Filtro, EstruturaGrid FROM  [vFiltrosConsultas]  where NombreConsultaUsuario='" & cNombreConsultaUsuario & "' AND IdUsuario='" & txtIdUsuario.Text & "' AND NombreConsulta='ConsultaEmisiones'")
        Dim MyRow As DataRow
        Dim cStringFiltro As String = ""
        Dim cSettingGrid As String = ""
        Dim LoadPersister As New GridSettingsPersister(RadGrid1)

        For Each MyRow In ds.Tables(0).Rows
            If Not IsDBNull(MyRow.Item("idConsulta")) Then txtIdConsulta.Text = Trim(MyRow.Item("idConsulta"))
            If Not IsDBNull(MyRow.Item("Filtro")) Then cStringFiltro = Trim(MyRow.Item("Filtro"))
            If Not IsDBNull(MyRow.Item("EstruturaGrid")) Then cSettingGrid = Trim(MyRow.Item("EstruturaGrid"))
        Next

        If cStringFiltro.Trim <> "" Then

            RadToolBar1.Items.Item(5).Text = cNombreConsultaUsuario

            Try
                With RadFilter1
                    .LoadSettings(cStringFiltro)
                    .RecreateControl()
                    .FireApplyCommand()
                End With
            Catch ex As Exception
                Throw
            End Try




        End If

        If cSettingGrid.Trim <> "" Then
            LoadPersister.LoadSettings(cSettingGrid)
            RadGrid1.Rebind()
        End If

    End Sub
    Protected Sub LlenarInformacionListaFiltros()
        'Carga cuando inicia la pagina

        Dim ds As DataSet = oper.ExDataSet("SELECT NombreConsultaUsuario FROM  [vFiltrosConsultas]  where IdUsuario='" & txtIdUsuario.Text & "' AND NombreConsulta='ConsultaEmisiones'")
        Dim MyRow As DataRow
        Dim cStringFiltro As String = ""


        Dim dropDownFiltro As RadToolBarDropDown = New RadToolBarDropDown("Ver consultas")
        RadToolBar1.Items.Add(dropDownFiltro)

        If ds.Tables(0).Rows.Count > 0 Then
            For Each MyRow In ds.Tables(0).Rows
                If Not IsDBNull(MyRow.Item("NombreConsultaUsuario")) Then cStringFiltro = Trim(MyRow.Item("NombreConsultaUsuario"))
                AgregarBotones(dropDownFiltro, cStringFiltro)
            Next
        End If

    End Sub
    Protected Sub LlenarInformacionListaFiltros1()

        Dim ds As DataSet = oper.ExDataSet("SELECT NombreConsultaUsuario FROM  [FiltrosConsultas]  where IdUsuario='" & txtIdUsuario.Text & "' AND NombreConsulta='ConsultaEmisiones' ORDER BY idConsulta ASC")
        Dim MyRow As DataRow
        Dim cStringFiltro As String = ""


        Dim dropDownFiltro As RadToolBarDropDown = RadToolBar1.Items.FindItemByText("Ver consultas")
        dropDownFiltro.Buttons.Clear()

        For Each MyRow In ds.Tables(0).Rows
            If Not IsDBNull(MyRow.Item("NombreConsultaUsuario")) Then cStringFiltro = Trim(MyRow.Item("NombreConsultaUsuario"))
            AgregarBotones(dropDownFiltro, cStringFiltro)
        Next

    End Sub
    Sub AgregarBotones(dropDownFiltro As RadToolBarDropDown, texto As String)
        Dim BotFiltros As RadToolBarButton = New RadToolBarButton(texto, False, "AlignGroup")
        dropDownFiltro.Buttons.Add(BotFiltros)
    End Sub


    Protected Sub RadGrid1_PageSizeChanged(sender As Object, e As GridPageSizeChangedEventArgs) Handles RadGrid1.PageSizeChanged
        With RadFilter1
            .FireApplyCommand()
        End With
        AnchoColumna()
    End Sub

    Protected Sub RadGrid1_PageIndexChanged(sender As Object, e As GridPageChangedEventArgs) Handles RadGrid1.PageIndexChanged

        With RadFilter1
            .FireApplyCommand()
        End With
        AnchoColumna()

    End Sub


    Protected Sub RadGrid1_GroupsChanging(sender As Object, e As GridGroupsChangingEventArgs) Handles RadGrid1.GroupsChanging
        With RadFilter1
            .FireApplyCommand()
        End With
    End Sub

    Protected Sub RadGrid1_SortCommand(sender As Object, e As GridSortCommandEventArgs) Handles RadGrid1.SortCommand
        With RadFilter1
            .FireApplyCommand()
        End With
    End Sub

    Protected Sub RadGrid1_ColumnsReorder(sender As Object, e As GridColumnsReorderEventArgs) Handles RadGrid1.ColumnsReorder
        With RadFilter1
            .FireApplyCommand()
        End With
    End Sub




End Class
